version: '3.8'

services:
  keycloak:
    container_name: keycloak-cv
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command:
      - "start-dev"
